### ISSUE TITLE
setTileLayer does not remove the previous layer

### ISSUE THREAD

**Issue by Antho1989** [xdev-software/vaadin-maps-leaflet-flow#127]
This cause the browser to continue to request openstreetmap.org in addition to the configured layer. A basic fix is easy, just removing the previous layer.

Add line `this.tile.remove(this.map);` line 62 of leafletCon.js

It would be a nice feature to be able to set the tile layer in constructor (with my fix, browser start to load the bad tiles and cancel the request immediately)

**Comment by JohannesRabauer** [comment]
Hi @Antho1989,
this seems to no longer be the case.
To test this, i added following code at https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/LeafletView.java#L93
After clicking the button, the tile layer changed without exceptions.

``` java
		this.map.setTileLayer(new LTileLayer(
			"https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png'",
			"© <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a>",
			17
		));
```

As for your suggestion with the TileLayer in the LMap constructor: This is addressed in the https://github.com/xdev-software/vaadin-maps-leaflet-flow/pull/201 and is now implemented.
