### ISSUE TITLE
Cannot update marker position

### ISSUE THREAD

**Issue by shalomcrown** [xdev-software/vaadin-maps-leaflet-flow#187]
When I try to update a marker, I receive an exception.
Looks like the problem is that you remove the lat and then set at position 0 in the array. You should just use 'set' without first removing.

`public void setLat(final double lat)
	{
		this.geometry.getCoordinates().remove(0);
		this.geometry.getCoordinates().set(0, lat);
	}
	
	public double getLon()
	{
		return this.geometry.getCoordinates().get(1);
	}
	
	public void setLon(final double lon)
	{
		this.geometry.getCoordinates().remove(1);
		this.geometry.getCoordinates().set(1, lon);
	}`

**Comment by JohannesRabauer** [comment]
This issue was brought to our attention by Károly at the vaadin-directory: https://vaadin.com/directory/component/leafletmap-for-vaadin/discussions
If fixed, one should comment this there too.
