### ISSUE TITLE
Exception is thrown during JavaScript execution

### ISSUE THREAD

**Issue by g4mbitos** [xdev-software/vaadin-maps-leaflet-flow#254]
Hello, I tried add Map() in my layout in kotlin: 

@Route(value = "map", layout = MainLayout::class)
@PageTitle("Map")
class MapView : VerticalLayout() {
 init {
        setSizeFull()
        add(LMap())
    }
}

There are these errors:

Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.

The error has occurred in the JS code: '$0, return (function() { this.map=new L.map(this.getElementsByTagName('div')[0]);}).apply($0)'

Uncaught ReferenceError: L is not defined (http://localhost:8080/VAADIN/build/FlowClient-d5d5e377.js:1:7757)

Uncaught TypeError: Cannot read properties of undefined (reading 'invalidateSize') (http://localhost:8080/map:4:34)
![error](https://github.com/xdev-software/vaadin-maps-leaflet-flow/assets/25308412/36cc66cf-2a6e-44a1-9a65-2daa59dacc06)

**Comment by techteam-bln** [comment]
Possibly the same error for me.

Vaadin: 24.1.3
Plugin Version: 3.0.1

> Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { this.map=new L.map(this.getElementsByTagName('div')[0]);}).apply($0)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { this.map.setView([49.675126, 12.160733], 17);}).apply($0)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { this.map.setView([49.675126, 12.160733], 17);}).apply($0)'
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, return (function() { if (this.tilelayer) {this.map.removeLayer(this.tilelayer);} this.tilelayer = L.tileLayer('https:\/\/{s}.tile.openstreetmap.org\/{z}\/{x}\/{y}.png',{attribution: '\u00A9 <a href=\"https:\/\/www.openstreetmap.org\/copyright\">OpenStreetMap<\/a>', maxZoom: 18}).addTo(this.map);}).apply($0)'
ReferenceError: L is not defined (http://localhost:8080/VAADIN/build/FlowClient-d5d5e377.js line 3 > Function:3:22)
TypeError: this.map is undefined (http://localhost:8080/VAADIN/build/FlowClient-d5d5e377.js line 3 > Function:3:22)
TypeError: this.map is undefined (http://localhost:8080/VAADIN/build/FlowClient-d5d5e377.js line 3 > Function:3:22)
ReferenceError: L is not defined (http://localhost:8080/VAADIN/build/FlowClient-d5d5e377.js line 3 > Function:4:1)
TypeError: tempMap is undefined (http://localhost:8080/VAADIN/build/FlowClient-d5d5e377.js line 3 > Function:4:26)

**Comment by AB-xdev** [comment]
Looks like the NPM dependency leaflet is missing.

I tried to reproduce the issue:
I downloaded the [Vaadin Starter](https://vaadin.com/hello-world-starters) (Spring Boot), added our dependency, added the MainView & MainLayout, did a ``prepare-frontend`` and started the Application.java.

Everything works fine.

Could you please provide a minimal reproducible example in the form of a repository?

**Comment by koendecock** [comment]
Same issue on my side, @g4mbitos @techteam-bln , were you able to resolve this on your end?

**Comment by AB-xdev** [comment]
Feel free to reopen the issue when a minimal reproducible example is provided

**Comment by bjmdev** [comment]
In case anyone is still interested: had the same problem. Solution was, to add "software/xdev" to vaadin.whitelisted-packages
