### ISSUE TITLE
Leaflet Layer Control and Layer Groups

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/vaadin-maps-leaflet-flow#268]
For original idea see: https://github.com/xdev-software/vaadin-maps-leaflet-flow/pull/182

**Comment by AB-xdev** [comment]
Current implementation is very difficult as we currently just create the component once and then forget about it. This doesn't allow thing like modification or adding the same component to 2 different things like a ``LMap`` and a ``LLayerControl``.

I think we might redesign this as with #267.

**Comment by evanpenner** [comment]
I recommend implementing the javascript in a way that allows easy support for other leaflet libraries. Perhaps letting the map class handle the adding and the LComponent could stay as its own Javascript object.

**Comment by evanpenner** [comment]
I recommend implementing the javascript in a way that allows easy support for other leaflet libraries. Perhaps letting the map class handle the adding and the LComponent could stay as its own Javascript object.
