### ISSUE TITLE
How can i locate a button right on the map.

### ISSUE THREAD

**Issue by lazizbektulanov** [xdev-software/vaadin-maps-leaflet-flow#317]
I want to locate a button in top left of the map, it should be placed right on the map so that on click this button i want to show a dialog which will include filters for the markers of the map.

**Comment by AB-xdev** [comment]
Hi, this sounds like a leaflet specific question.

I assume you need something similar like we have inside the "complex demo", utilizing [Layer](https://leafletjs.com/reference.html#layergroup)/[FeatureGroups](https://leafletjs.com/reference.html#featuregroup):
https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/3b5d616ef4c74f3c03e601654815a18183391ad8/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/ComplexDemo.java#L166-L171

You can the add LayerGroups as [ControlLayer](https://leafletjs.com/reference.html#control-layers):
https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/3b5d616ef4c74f3c03e601654815a18183391ad8/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/ComplexDemo.java#L207-L213

which looks e.g. like this when expanded:
![grafik](https://github.com/xdev-software/vaadin-maps-leaflet-flow/assets/45384811/03fbd63f-be0a-49c9-81c6-b31d0b42c4c9)

**Comment by AB-xdev** [comment]
Closing due to lack of feedback
