### ISSUE TITLE
Use of LMapZoomPanOptions results in "Uncaught SyntaxError: missing ) after argument list"

### ISSUE THREAD

**Issue by Aklakan** [xdev-software/vaadin-maps-leaflet-flow#330]
Using `com.xdev-software:vaadin-maps-leaflet-flow:4.1.0`.

The following snippet creates an invalid JavaScript payload:
```java
LMapZoomPanOptions opts = new LMapZoomPanOptions();
opts.setDuration(1.0);
map.flyToBounds(bounds, opts);
```

The reason is, that several produced strings such as in [LMap#435](https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/map/LMap.java#L435) lack the `,` when options are present.

For example, I get the incorrect payload:
```javascript
document.getElementById('lComponentRegistry1').lComponents.get(1).flyToBounds(
    document.getElementById('lComponentRegistry1').lComponents.get(31){"duration":1.0})
```

The correct payload would be `...get(31), {"duration":1.0})`

**Comment by AB-xdev** [comment]
Thank you for the issue.

This was indeed incorrect.
I also found some other methods that build invalid Javascript.

The fix will be shipped with the next release
