### ISSUE TITLE
how do i load a local image map in to Leaflet-Maps?

### ISSUE THREAD

**Issue by emaayan** [xdev-software/vaadin-maps-leaflet-flow#333]
i'd like to load a custom local image instead of an internet map, and use cm as x,y coordinates (assuming i have the pixel scale), is that possible?

**Comment by AB-xdev** [comment]
Yes, this sounds like https://leafletjs.com/examples/crs-simple/crs-simple.html

I did [some minor tweaks](https://github.com/xdev-software/vaadin-maps-leaflet-flow/commit/59380c0cee450f919fc811865aace92433a1288e) (that will be available in the next release) and added [a demo how this can be done with the java library](https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/NotOfThisEarthDemo.java).

I hope this helps :)

**Comment by emaayan** [comment]
thanks,that does help, still trying to get my head around all the zoom
thing and how come some map image appear zoomed in ..
