### ISSUE TITLE
Displaying a legend on a map

### ISSUE THREAD

**Issue by padmalcom** [xdev-software/vaadin-maps-leaflet-flow#335]
Hi, I tried to add a legend with icons and text to a map and found the JS example with leaflet:

https://codepen.io/haakseth/pen/KQbjdO

Trying to reproduce in java lacks information on my side to create an LControl instance. Can you give me some guidance?

Thanks in advance.

**Comment by AB-xdev** [comment]
Hmm so this example calls ``L.control({ ... })`` however I couldn't the leaflet docs stating anywhere that this class can be instantiated in such a way.

I think it would be better if you extend the [component accordingly](https://leafletjs.com/examples/extending/extending-3-controls.html#controls) with e.g. a piece of JavaScript

**Comment by AB-xdev** [comment]
I added a demo how to do this:
https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/WatermarkControlDemo.java

**Comment by padmalcom** [comment]
Your support leaves me speechless. Thanks a lot!
