### ISSUE TITLE
[Question] Is it possible to show a Image or any other Vaadin Component in a Marker PopUp

### ISSUE THREAD

**Issue by IBims1ckoky** [xdev-software/vaadin-maps-leaflet-flow#336]
Hey XDEV-Team!
 Is it possible to show a Image or any other Vaadin Component in a Marker PopUp Menu?
Currently I only get it (with the following code) to add a marker that adds a text on the marker:

Thanks! 😄 

```java
  new LPopup(reg, new LLatLng(reg, lat, lng))
        .bindPopup("I am a PopUp Text")
        .addTo(map);
```

**Comment by AB-xdev** [comment]
Had some quick thoughts about this and came to the following conclusion:
Currently as far as I know: Yes and no.

You can e.g. create certain/simple Vaadin components let's say an ``Image`` get the HTML content and then add them.
However the component can only be used for creation. Communication, like updating the ``src`` of the image from the server side will not be possible.

Example:
```java
new LPopup(reg, new LLatLng(reg, lat, lng))
        .bindPopup(new Image("pathToImage", "Failed to load picture").getElement().getOuterHtml())
        .addTo(map);
```

Hope that helps :)

**Comment by IBims1ckoky** [comment]
Hi @AB-xdev,
i have another question, but I think it's probably more Vaadin-related..

I want that a button is placed above the map 🙂
I don't mean that the button is actually on the map, but is simply a component above the map component. is that possible? how can i do that 😄

**Comment by AB-xdev** [comment]
This sounds like https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues/335 (however this likely won't work with a Vaadin component).
As an alternative you might also use [html overlaying](https://stackoverflow.com/a/46318225) using the ``position`` attribute or something similar.
