### ISSUE TITLE
How to get access to the LMap instance?

### ISSUE THREAD

**Issue by padmalcom** [xdev-software/vaadin-maps-leaflet-flow#341]
Hi sorry to disturb again. Is there a way to get the instance of the LMap in JavaScript? I know that I can get the js accessor using `map.clientComponentJsAccessor()`. But this is a string, not the LMap object. Is there a way?

**Comment by AB-xdev** [comment]
When calling ``LMap#clientComponentJsAccessor`` on the Java side I get something like this:
``document.getElementById('lComponentRegistry1').lComponents.get(1)``

Which is a valid JavaScript code to get the ``LMap``.

An example how this can be used can be seen in https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/52f5ad563db529e84578e547b53893f44c08a722/vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/map/LMap.java#L89-L93

If you want to access this client side without server interaction you can save the map at creation somewhere e.g. with 
```java
this.componentRegistry().execJs("document.myCoolMap = " + this.clientComponentJsAccessor() + "; " );

// or better
this.componentRegistry().execJs("document.getElementById('myStorageElement').myCoolMap = " 
  + this.clientComponentJsAccessor() + "; " );
```
