### ISSUE TITLE
can leaflet handle hundreds of moving markers?

### ISSUE THREAD

**Issue by emaayan** [xdev-software/vaadin-maps-leaflet-flow#346]
is it possible to use leaflet to show in real time location changes in real time of markers? 
do you happen to have a sample for it?

**Comment by AB-xdev** [comment]
Hi, 
1. https://www.google.com/search?q=leaflet+is+it+possible+to+use+leaflet+to+show+in+real+time+location+changes+in+real+time+of+markers <br/>→ https://gis.stackexchange.com/questions/259969/leaflet-how-to-update-user-position-marker-real-time
2. no we currently don't have a sample for that

**Comment by emaayan** [comment]
thanks, didn't occur to me to look for the exact phrase, looking at the sample i might be a too noobe here i dont' see a java comprarble way of attaching locationEvents, or is it just javascript, but eventualy it's still just deleting and creating new markers, 
question is will this scale to thousands of markers. or hunderds.

**Comment by AB-xdev** [comment]
> will this scale to thousands of markers. or hunderds

Should be possible, but depends on the underlying hardware.
