### ISSUE TITLE
Edit map data

### ISSUE THREAD

**Issue by plingsi** [xdev-software/vaadin-maps-leaflet-flow#353]
Hi,
we are considering moving to this framework. Are there any plans for implementing support for edit polygons, lines etc?

**Comment by AB-xdev** [comment]
> Are there any plans for implementing support for edit polygons, lines etc?

I don't understand the question fully as we already support most methods of leaflet, including methods that allow editing components such as [``setLatLngs``](https://leafletjs.com/reference.html#polyline-setlatlngs).
Didn't this work in your case?
