### ISSUE TITLE
L.GeoJson Layer

### ISSUE THREAD

**Issue by TmCoop** [xdev-software/vaadin-maps-leaflet-flow#438]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues) or [closed](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

Hello, I want to user your Plugin for an  Vaadin Application. The Problem is, that I need to Implement Overlaylayer wich based on GeoJson date. 

Is it possible to implemnt the geoJson Layer functions from leaflet.js

greetings
Tobi

**Comment by AB-xdev** [comment]
Implemented in https://github.com/xdev-software/vaadin-maps-leaflet-flow/commit/ca4a4eadf961fcdacefe5ab2adf53bdf77adb796 should be available with the next release.

You can find a demo how to use it here:
https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/GeoJSONDemo.java
