### ISSUE TITLE
L is not defined 

### ISSUE THREAD

**Issue by TmCoop** [xdev-software/vaadin-maps-leaflet-flow#442]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/vaadin-maps-leaflet-flow/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues) or [closed](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

4.4.0

### Steps to reproduce the bug

1. I tried first implement an Basic Map with OSM as base Layer like in the Documentation but in the Browser console I always get the not defined Errors.
2. the pom is correct but I aleays get the message that leaflet is not inside of the bundle
3.
![image](https://github.com/user-attachments/assets/3415e525-7358-4565-8aff-506af09b7d18)

**Comment by AB-xdev** [comment]
The problem usually indicates some kind of build failure.
Maybe Vaadin's bundle is missing Leaflet, in this case try to rebuild it.


We had a similar problem in 
https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues/254

From our release page:

> ### Additional notes
> * [Spring-Boot] You may have to include ``software/xdev`` inside [``vaadin.allowed-packages``](https://vaadin.com/docs/latest/integrations/spring/configuration#configure-the-scanning-of-packages)

----

If you are using Quarkus you might have to enable indexing: https://github.com/xdev-software/vaadin-date-range-picker/issues/352
