### ISSUE TITLE
Change Layer Color

### ISSUE THREAD

**Issue by TmCoop** [xdev-software/vaadin-maps-leaflet-flow#443]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues) or [closed](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

how I can change the color of an Layer

**Comment by AB-xdev** [comment]
> how I can change the color of an Layer

Not sure what is meant with that as layers don't have a direct color and usually contain specific elements (e.g. a marker or a rectangle) whose color can be changed.

For example a rectangle fill color can be changed using:
https://leafletjs.com/reference.html#rectangle-fillcolor

Please also note that is is not directly related to our component and maybe have a look at the [Leaflet docs](https://leafletjs.com/reference.html) instead ;)

**Comment by TmCoop** [comment]
I vant to implemtn this in Java but i didn`t find any solution: 
L.geoJSON(vgrBeBernUmgebungFeatureExt, { style: function () {return {color: "#8604ba"}}
        })

**Comment by TmCoop** [comment]
it works thankyou
