### ISSUE TITLE
Treeview in LayerControl

### ISSUE THREAD

**Issue by TmCoop** [xdev-software/vaadin-maps-leaflet-flow#457]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues) or [closed](https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

hi ist ist possible to integrate https://github.com/jjimenezshaw/Leaflet.Control.Layers.Tree into your wrapper? or the same function

**Comment by AB-xdev** [comment]
Moved to/Integrated into #307

Feel free to give it an upvote
