### ISSUE TITLE
Leaftletmap overrides Vaadin dialogs

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/vaadin-maps-leaflet-flow#58]
If you open a Vaadin dialog in front of the leafletmap, that dialog is hidden behind the leafletmap.

Looks like the z-index is not set correctly.

Possible solution:
Set z-index by default to 1.

**Comment by mh-xdev** [comment]
I'll look into this. It appears that this issue would require a fix to #59, so I'll be looking into fixing that one at the same time.
